[[rulesets]]
group = "REJECT"
ruleset = "rules/ACL4SSR/Clash/BanAD.list"

[[rulesets]]
group = "REJECT"
ruleset = "rules/ACL4SSR/Clash/BanEasyList.list"

[[rulesets]]
group = "REJECT"
ruleset = "rules/ACL4SSR/Clash/BanProgramAD.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/ChinaDomain.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/ACL4SSR/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "🔰 节点选择"
ruleset = "[]FINAL"
